---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  clusterIP: None
  ports:
  - port: 27017
  selector:
    app: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: docker.io/mongo
        env:
        - name: DB_ADAPTER
          value: 'mongo'
        - name: DB_HOST
          value: 'mongo'
        - name: DB_DATABASE
          value: 'konga'
        - name: NODE_ENV
          value: 'development'
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  # do not use these in production use Flocker or other ssd pd
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: gold
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: gold
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd